spring:
  application:
    name: Info Store API
  main:
    banner-mode: OFF
  datasource:
    url: jdbc:postgresql://infostore-db:5432/infostore_platform?currentSchema=platform_data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

server:
  port: 8081